version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./uploads/files:/app/uploads/files
      - /var/tmp:/var/tmp
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=run.py
      - IS_DOCKER=true
    depends_on:
      - db
      - selenium
#    restart: always

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome:dev
    platform: linux/amd64
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSION=1

volumes:
  postgres_data:
  pgadmin-data:
