"""empty message

Revision ID: 0ffa0f4134a1
Revises: 
Create Date: 2024-01-18 23:03:11.141535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffa0f4134a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('html_code', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('whois_protocol', sa.Text(), nullable=True),
    sa.Column('network_info', sa.Text(), nullable=True),
    sa.Column('archived_page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archived_page_id'], ['archived_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_info')
    op.drop_table('archived_page')
    # ### end Alembic commands ###
