"""added protected_flag

Revision ID: 4b8662853bff
Revises: 
Create Date: 2025-04-26 14:56:11.286214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8662853bff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.drop_column('protected')

    # ### end Alembic commands ###
