"""add user_service_ex

Revision ID: 8815b51a334d
Revises: b3f99eb4c30b
Create Date: 2024-06-07 00:54:39.751578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8815b51a334d'
down_revision = 'b3f99eb4c30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_archived_page_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_service_ex', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_archived_page_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
