"""empty message

Revision ID: 927fd6b33998
Revises: ad29dea2f3bb
Create Date: 2024-01-19 00:17:40.924934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '927fd6b33998'
down_revision = 'ad29dea2f3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.Text(), nullable=True))
        batch_op.drop_column('html_code')

    with op.batch_alter_table('domain_info', schema=None) as batch_op:
        batch_op.alter_column('network_info',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_info', schema=None) as batch_op:
        batch_op.alter_column('network_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_code', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
