"""Описание изменений

Revision ID: bd5f5f7e6582
Revises: 927fd6b33998
Create Date: 2024-01-19 00:25:10.267764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5f5f7e6582'
down_revision = '927fd6b33998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.Text(), nullable=True))
        batch_op.drop_column('html_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_code', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
