"""empty message

Revision ID: f9fa579ddc85
Revises: bd5f5f7e6582
Create Date: 2024-01-19 01:38:26.410934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fa579ddc85'
down_revision = 'bd5f5f7e6582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_code', sa.Text(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('html_code')

    # ### end Alembic commands ###
